#ifndef COMMAND_RESPONSE_TYPE_H
#define COMMAND_RESPONSE_TYPE_H
#include <stdint.h>

enum class CommandResponseType : uint8_t {
    ACK,
    ERROR,
    ROBOT_STATUS,
    SYSTEM_STATUS,
    MOTION_STATUS,
    WIFI_STATUS,
    ROBOT_CONFIG,
    MOTION_CONFIG,
    WIFI_CONFIG,
    WIFI_STATION_CREDENTIALS,
    WIFI_ACCESS_POINT_CREDENTIALS
};
#endif
